# Use official Nginx image
FROM nginx:alpine

# Copy your portfolio page into nginx's web folder
COPY index.html /usr/share/nginx/html/index.html

# Expose port 80
EXPOSE 80

# Default command
CMD ["nginx", "-g", "daemon off;"]
